export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'admin' | 'game_master' | 'customer_service' | 'customer';
export type BookingType = 'general' | 'corporate' | 'birthday' | 'vip';
export type BookingStatus = 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'no_show' | 'approved' | 'rejected';
export type PaymentStatus = 'pending' | 'paid' | 'refunded' | 'failed' | 'partially_paid';
export type PaymentMethod = 'card' | 'cash' | 'apple_pay' | 'google_pay' | 'bank_transfer';
export type OrderType = 'booking' | 'merchandise' | 'pos' | 'lobby_game';
export type ReviewSource = 'google' | 'tripadvisor' | 'website' | 'onsite';
export type DifficultyLevel = 'easy' | 'medium' | 'hard' | 'expert';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          role: UserRole;
          avatar_url: string | null;
          preferences: Json;
          welcome_email_sent: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          phone?: string | null;
          role?: UserRole;
          avatar_url?: string | null;
          preferences?: Json;
          welcome_email_sent?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          phone?: string | null;
          role?: UserRole;
          avatar_url?: string | null;
          preferences?: Json;
          welcome_email_sent?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      games: {
        Row: {
          id: string;
          name: string;
          slug: string;
          storyline: string | null;
          description: string | null;
          difficulty: DifficultyLevel | null;
          duration_minutes: number | null;
          min_players: number | null;
          max_players: number | null;
          base_price: number | null;
          room_number: string | null;
          image_url: string | null;
          gallery_urls: string[] | null;
          status: string | null;
          features: Json;
          meta_title: string | null;
          meta_description: string | null;
          created_at: string;
          updated_at: string;
          tagline: string | null;
          mission_objectives: Json;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          storyline?: string | null;
          description?: string | null;
          difficulty?: DifficultyLevel | null;
          duration_minutes?: number | null;
          min_players?: number | null;
          max_players?: number | null;
          base_price?: number | null;
          room_number?: string | null;
          image_url?: string | null;
          gallery_urls?: string[] | null;
          status?: string | null;
          features?: Json;
          meta_title?: string | null;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
          tagline?: string | null;
          mission_objectives?: Json;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          storyline?: string | null;
          description?: string | null;
          difficulty?: DifficultyLevel | null;
          duration_minutes?: number | null;
          min_players?: number | null;
          max_players?: number | null;
          base_price?: number | null;
          room_number?: string | null;
          image_url?: string | null;
          gallery_urls?: string[] | null;
          status?: string | null;
          features?: Json;
          meta_title?: string | null;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
          tagline?: string | null;
          mission_objectives?: Json;
        };
        Relationships: [];
      };
      bookings: {
        Row: {
          id: string;
          booking_number: string;
          user_id: string | null;
          game_id: string | null;
          booking_type: BookingType | null;
          booking_status: BookingStatus | null;
          booking_date: string | null;
          start_time: string | null;
          end_time: string | null;
          number_of_players: number | null;
          customer_name: string | null;
          customer_email: string | null;
          customer_phone: string | null;
          billing_address: Json | null;
          special_requests: string | null;
          total_amount: number | null;
          discount_amount: number | null;
          final_amount: number | null;
          payment_status: PaymentStatus | null;
          payment_method: PaymentMethod | null;
          promo_code_id: string | null;
          confirmed_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
          cancelled_by: string | null;
          cancellation_reason: string | null;
          reminder_sent: boolean | null;
          created_at: string;
          updated_at: string;
          booking_slot_id: string | null;
          allow_overbooking: boolean | null;
          booking_type_id: string | null;
          requires_approval: boolean | null;
          approval_status: string | null;
          approved_by: string | null;
          approved_at: string | null;
          rejection_reason: string | null;
          subtotal: number | null;
          vat_amount: number | null;
          confirmation_required: boolean | null;
          confirmed_by_customer_at: string | null;
          confirmation_method: string | null;
          lobby_game_id: string | null;
          referral_source: string | null;
        };
        Insert: {
          id?: string;
          booking_number?: string;
          user_id?: string | null;
          game_id?: string | null;
          booking_type?: BookingType | null;
          booking_status?: BookingStatus | null;
          booking_date?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          number_of_players?: number | null;
          customer_name?: string | null;
          customer_email?: string | null;
          customer_phone?: string | null;
          special_requests?: string | null;
          total_amount?: number | null;
          discount_amount?: number | null;
          final_amount?: number | null;
          payment_status?: PaymentStatus | null;
          payment_method?: PaymentMethod | null;
          promo_code_id?: string | null;
          confirmed_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancelled_by?: string | null;
          cancellation_reason?: string | null;
          reminder_sent?: boolean | null;
          created_at?: string;
          updated_at?: string;
          booking_slot_id?: string | null;
          allow_overbooking?: boolean | null;
          booking_type_id?: string | null;
          requires_approval?: boolean | null;
          approval_status?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          rejection_reason?: string | null;
          subtotal?: number | null;
          vat_amount?: number | null;
          confirmation_required?: boolean | null;
          confirmed_by_customer_at?: string | null;
          confirmation_method?: string | null;
          lobby_game_id?: string | null;
          referral_source?: string | null;
        };
        Update: {
          id?: string;
          booking_number?: string;
          user_id?: string | null;
          game_id?: string | null;
          booking_type?: BookingType | null;
          booking_status?: BookingStatus | null;
          booking_date?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          number_of_players?: number | null;
          customer_name?: string | null;
          customer_email?: string | null;
          customer_phone?: string | null;
          special_requests?: string | null;
          total_amount?: number | null;
          discount_amount?: number | null;
          final_amount?: number | null;
          payment_status?: PaymentStatus | null;
          payment_method?: PaymentMethod | null;
          promo_code_id?: string | null;
          confirmed_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          reminder_sent?: boolean | null;
          created_at?: string;
          updated_at?: string;
          booking_slot_id?: string | null;
          allow_overbooking?: boolean | null;
          booking_type_id?: string | null;
          requires_approval?: boolean | null;
          approval_status?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          rejection_reason?: string | null;
          subtotal?: number | null;
          vat_amount?: number | null;
          confirmation_required?: boolean | null;
          confirmed_by_customer_at?: string | null;
          confirmation_method?: string | null;
          lobby_game_id?: string | null;
          referral_source?: string | null;
        };
        Relationships: [];
      };
      booking_participants: {
        Row: {
          id: string;
          booking_id: string;
          full_name: string;
          phone_number: string | null;
          age: number | null;
          waiver_signed: boolean | null;
          waiver_signed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          full_name: string;
          phone_number?: string | null;
          age?: number | null;
          waiver_signed?: boolean | null;
          waiver_signed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          full_name?: string;
          phone_number?: string | null;
          age?: number | null;
          waiver_signed?: boolean | null;
          waiver_signed_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      booking_slots: {
        Row: {
          id: string;
          game_schedule_id: string;
          slot_date: string;
          start_time: string;
          end_time: string;
          is_available: boolean | null;
          max_participants: number;
          current_participants: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          game_schedule_id: string;
          slot_date: string;
          start_time: string;
          end_time: string;
          is_available?: boolean | null;
          max_participants?: number;
          current_participants?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          game_schedule_id?: string;
          slot_date?: string;
          start_time?: string;
          end_time?: string;
          is_available?: boolean | null;
          max_participants?: number;
          current_participants?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      chat_conversations: {
        Row: {
          id: string;
          session_id: string;
          user_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      chat_messages: {
        Row: {
          id: string;
          conversation_id: string;
          role: string;
          content: string;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          role: string;
          content: string;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          role?: string;
          content?: string;
          metadata?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      game_schedules: {
        Row: {
          id: string;
          game_id: string;
          day_of_week: number;
          start_time: string;
          duration_minutes: number;
          max_participants: number;
          is_active: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          day_of_week: number;
          start_time: string;
          duration_minutes?: number;
          max_participants?: number;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string;
          day_of_week?: number;
          start_time?: string;
          duration_minutes?: number;
          max_participants?: number;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      merchandise: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          category: string | null;
          game_id: string | null;
          base_price: number | null;
          stock_quantity: number | null;
          low_stock_threshold: number | null;
          sku: string | null;
          image_url: string | null;
          gallery_urls: string[] | null;
          variants: Json;
          is_available: boolean | null;
          meta_title: string | null;
          meta_description: string | null;
          created_at: string;
          updated_at: string;
          cost_price: number | null;
          has_variants: boolean | null;
          attributes_schema: Json;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          category?: string | null;
          game_id?: string | null;
          base_price?: number | null;
          stock_quantity?: number | null;
          low_stock_threshold?: number | null;
          sku?: string | null;
          image_url?: string | null;
          gallery_urls?: string[] | null;
          variants?: Json;
          is_available?: boolean | null;
          meta_title?: string | null;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
          cost_price?: number | null;
          has_variants?: boolean | null;
          attributes_schema?: Json;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          category?: string | null;
          game_id?: string | null;
          base_price?: number | null;
          stock_quantity?: number | null;
          low_stock_threshold?: number | null;
          sku?: string | null;
          image_url?: string | null;
          gallery_urls?: string[] | null;
          variants?: Json;
          is_available?: boolean | null;
          meta_title?: string | null;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
          cost_price?: number | null;
          has_variants?: boolean | null;
          attributes_schema?: Json;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          user_id: string | null;
          booking_id: string | null;
          order_type: OrderType | null;
          total_amount: number | null;
          discount_amount: number | null;
          final_amount: number | null;
          payment_status: PaymentStatus | null;
          payment_method: PaymentMethod | null;
          promo_code_id: string | null;
          customer_name: string | null;
          customer_email: string | null;
          customer_phone: string | null;
          shipping_address: Json | null;
          notes: string | null;
          pos_session_id: string | null;
          created_at: string;
          updated_at: string;
          subtotal: number | null;
          vat_amount: number | null;
        };
        Insert: {
          id?: string;
          order_number?: string;
          user_id?: string | null;
          booking_id?: string | null;
          order_type?: OrderType | null;
          total_amount?: number | null;
          discount_amount?: number | null;
          final_amount?: number | null;
          payment_status?: PaymentStatus | null;
          payment_method?: PaymentMethod | null;
          promo_code_id?: string | null;
          customer_name?: string | null;
          customer_email?: string | null;
          customer_phone?: string | null;
          shipping_address?: Json | null;
          notes?: string | null;
          pos_session_id?: string | null;
          created_at?: string;
          updated_at?: string;
          subtotal?: number | null;
          vat_amount?: number | null;
        };
        Update: {
          id?: string;
          order_number?: string;
          user_id?: string | null;
          booking_id?: string | null;
          order_type?: OrderType | null;
          total_amount?: number | null;
          discount_amount?: number | null;
          final_amount?: number | null;
          payment_status?: PaymentStatus | null;
          payment_method?: PaymentMethod | null;
          promo_code_id?: string | null;
          customer_name?: string | null;
          customer_email?: string | null;
          customer_phone?: string | null;
          shipping_address?: Json | null;
          notes?: string | null;
          pos_session_id?: string | null;
          created_at?: string;
          updated_at?: string;
          subtotal?: number | null;
          vat_amount?: number | null;
        };
        Relationships: [];
      };
      promo_codes: {
        Row: {
          id: string;
          code: string;
          description: string | null;
          discount_type: string | null;
          discount_value: number | null;
          min_purchase_amount: number | null;
          max_discount_amount: number | null;
          usage_limit: number | null;
          usage_count: number | null;
          valid_from: string | null;
          valid_until: string | null;
          is_active: boolean | null;
          applicable_to: string[] | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          description?: string | null;
          discount_type?: string | null;
          discount_value?: number | null;
          min_purchase_amount?: number | null;
          max_discount_amount?: number | null;
          usage_limit?: number | null;
          usage_count?: number | null;
          valid_from?: string | null;
          valid_until?: string | null;
          is_active?: boolean | null;
          applicable_to?: string[] | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          description?: string | null;
          discount_type?: string | null;
          discount_value?: number | null;
          min_purchase_amount?: number | null;
          max_discount_amount?: number | null;
          usage_limit?: number | null;
          usage_count?: number | null;
          valid_from?: string | null;
          valid_until?: string | null;
          is_active?: boolean | null;
          applicable_to?: string[] | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      promo_code_usage: {
        Row: {
          id: string;
          promo_code_id: string | null;
          user_id: string | null;
          booking_id: string | null;
          order_id: string | null;
          discount_applied: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          promo_code_id?: string | null;
          user_id?: string | null;
          booking_id?: string | null;
          order_id?: string | null;
          discount_applied?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          promo_code_id?: string | null;
          user_id?: string | null;
          booking_id?: string | null;
          order_id?: string | null;
          discount_applied?: number;
          created_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          user_id: string | null;
          booking_id: string | null;
          game_id: string | null;
          source: ReviewSource | null;
          rating: number | null;
          title: string | null;
          comment: string | null;
          reviewer_name: string | null;
          reviewer_email: string | null;
          is_verified: boolean | null;
          is_published: boolean | null;
          external_id: string | null;
          external_url: string | null;
          created_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          booking_id?: string | null;
          game_id?: string | null;
          source?: ReviewSource | null;
          rating?: number | null;
          title?: string | null;
          comment?: string | null;
          reviewer_name?: string | null;
          reviewer_email?: string | null;
          is_verified?: boolean | null;
          is_published?: boolean | null;
          external_id?: string | null;
          external_url?: string | null;
          created_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          booking_id?: string | null;
          game_id?: string | null;
          source?: ReviewSource | null;
          rating?: number | null;
          title?: string | null;
          comment?: string | null;
          reviewer_name?: string | null;
          reviewer_email?: string | null;
          is_verified?: boolean | null;
          is_published?: boolean | null;
          external_id?: string | null;
          external_url?: string | null;
          created_at?: string;
          published_at?: string | null;
        };
      };
      waivers: {
        Row: {
          id: string;
          user_id: string | null;
          booking_id: string | null;
          participant_name: string | null;
          participant_email: string | null;
          participant_phone: string | null;
          date_of_birth: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          signature_data: string | null;
          ip_address: string | null;
          signed_at: string;
          is_reusable: boolean | null;
          valid_until: string | null;
          created_at: string;
          waiver_template_id: string | null;
          template_version: string | null;
          template_title: string | null;
          template_content: string | null;
          game_id: string | null;
          game_name: string | null;
          player_number: number | null;
          waiver_status: string | null;
          lobby_game_id: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          booking_id?: string | null;
          participant_name?: string | null;
          participant_email?: string | null;
          participant_phone?: string | null;
          date_of_birth?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          signature_data?: string | null;
          ip_address?: string | null;
          signed_at?: string;
          is_reusable?: boolean | null;
          valid_until?: string | null;
          created_at?: string;
          waiver_template_id?: string | null;
          template_version?: string | null;
          template_title?: string | null;
          template_content?: string | null;
          game_id?: string | null;
          game_name?: string | null;
          player_number?: number | null;
          waiver_status?: string | null;
          lobby_game_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          booking_id?: string | null;
          participant_name?: string | null;
          participant_email?: string | null;
          participant_phone?: string | null;
          date_of_birth?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          signature_data?: string | null;
          ip_address?: string | null;
          signed_at?: string;
          is_reusable?: boolean | null;
          valid_until?: string | null;
          created_at?: string;
          waiver_template_id?: string | null;
          template_version?: string | null;
          template_title?: string | null;
          template_content?: string | null;
          game_id?: string | null;
          game_name?: string | null;
          player_number?: number | null;
          waiver_status?: string | null;
          lobby_game_id?: string | null;
        };
        Relationships: [];
      };
      waiver_templates: {
        Row: {
          id: string;
          title: string;
          content: string;
          version: string | null;
          is_active: boolean | null;
          is_required: boolean | null;
          applies_to: string[] | null;
          game_ids: string[] | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          content: string;
          version?: string | null;
          is_active?: boolean | null;
          is_required?: boolean | null;
          applies_to?: string[] | null;
          game_ids?: string[] | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          content?: string;
          version?: string | null;
          is_active?: boolean | null;
          is_required?: boolean | null;
          applies_to?: string[] | null;
          game_ids?: string[] | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      blog_posts: {
        Row: {
          id: string;
          title: string;
          slug: string;
          excerpt: string | null;
          content: string | null;
          featured_image: string | null;
          author_id: string | null;
          status: string | null;
          is_published: boolean | null;
          meta_title: string | null;
          meta_description: string | null;
          meta_keywords: string[] | null;
          published_at: string | null;
          created_at: string;
          updated_at: string;
          views: number | null;
          featured: boolean;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          excerpt?: string | null;
          content?: string | null;
          featured_image?: string | null;
          author_id?: string | null;
          status?: string | null;
          is_published?: boolean | null;
          meta_title?: string | null;
          meta_description?: string | null;
          meta_keywords?: string[] | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
          views?: number | null;
          featured?: boolean;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          excerpt?: string | null;
          content?: string | null;
          featured_image?: string | null;
          author_id?: string | null;
          status?: string | null;
          is_published?: boolean | null;
          meta_title?: string | null;
          meta_description?: string | null;
          meta_keywords?: string[] | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
          views?: number | null;
          featured?: boolean;
        };
      };
      static_pages: {
        Row: {
          id: string;
          title: string;
          slug: string;
          content: string | null;
          page_type: string | null;
          meta_title: string | null;
          meta_description: string | null;
          schema_markup: Json | null;
          is_published: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          content?: string | null;
          page_type?: string | null;
          meta_title?: string | null;
          meta_description?: string | null;
          schema_markup?: Json | null;
          is_published?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          content?: string | null;
          page_type?: string | null;
          meta_title?: string | null;
          meta_description?: string | null;
          schema_markup?: Json | null;
          is_published?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          invoice_number: string;
          booking_id: string | null;
          subtotal: number;
          tax_amount: number | null;
          discount_amount: number | null;
          total_amount: number;
          currency: string | null;
          status: string | null;
          issued_at: string | null;
          due_date: string | null;
          paid_at: string | null;
          created_at: string;
          updated_at: string;
          customer_name: string | null;
          customer_email: string | null;
          customer_phone: string | null;
          admin_discount_percentage: number | null;
          admin_discount_amount: number | null;
          admin_discount_reason: string | null;
          notes: string | null;
          payment_method: string | null;
          game_name: string | null;
          lobby_game_name: string | null;
          booking_type: string | null;
          amount_paid: number | null;
          updated_by: string | null;
          payment_reference: string | null;
          trn_number: string | null;
          pos_transaction_id?: string | null;
          customer_id?: string | null;
        };
        Insert: {
          id?: string;
          invoice_number?: string;
          booking_id?: string | null;
          subtotal?: number;
          tax_amount?: number | null;
          discount_amount?: number | null;
          total_amount?: number;
          currency?: string | null;
          status?: string | null;
          issued_at?: string | null;
          due_date?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
          customer_name?: string | null;
          customer_email?: string | null;
          customer_phone?: string | null;
          billing_address?: Json | null;
          admin_discount_percentage?: number | null;
          admin_discount_amount?: number | null;
          admin_discount_reason?: string | null;
          notes?: string | null;
          payment_method?: string | null;
          game_name?: string | null;
          lobby_game_name?: string | null;
          booking_type?: string | null;
          amount_paid?: number | null;
          updated_by?: string | null;
          payment_reference?: string | null;
          trn_number?: string | null;
          pos_transaction_id?: string | null;
          customer_id?: string | null;
        };
        Update: {
          id?: string;
          invoice_number?: string;
          booking_id?: string | null;
          subtotal?: number;
          tax_amount?: number | null;
          discount_amount?: number | null;
          total_amount?: number;
          currency?: string | null;
          status?: string | null;
          issued_at?: string | null;
          due_date?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
          customer_name?: string | null;
          customer_email?: string | null;
          customer_phone?: string | null;
          billing_address?: Json | null;
          admin_discount_percentage?: number | null;
          admin_discount_amount?: number | null;
          admin_discount_reason?: string | null;
          notes?: string | null;
          payment_method?: string | null;
          game_name?: string | null;
          lobby_game_name?: string | null;
          booking_type?: string | null;
          amount_paid?: number | null;
          updated_by?: string | null;
          payment_reference?: string | null;
          trn_number?: string | null;
          pos_transaction_id?: string | null;
          customer_id?: string | null;
        };
      };
      invoice_line_items: {
        Row: {
          id: string;
          invoice_id: string;
          product_name: string;
          quantity: number;
          unit_price: number;
          discount_amount: number | null;
          tax_amount: number | null;
          line_total: number | null;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          product_name: string;
          quantity: number;
          unit_price: number;
          discount_amount?: number | null;
          tax_amount?: number | null;
          line_total?: number | null;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          product_name?: string;
          quantity?: number;
          unit_price?: number;
          discount_amount?: number | null;
          tax_amount?: number | null;
          line_total?: number | null;
        };
        Relationships: [];
      };
      pos_transactions: {
        Row: {
          id: string;
          created_by: string | null;
          created_at: string;
          status: string | null;
          subtotal: number | null;
          tax: number | null;
          discount: number | null;
          total: number | null;
          payment_method: string | null;
          discount_type: string | null;
          discount_value: number | null;
          invoice_id: string | null;
        };
        Insert: {
          id?: string;
          created_by?: string | null;
          created_at?: string;
          status?: string | null;
          subtotal?: number | null;
          tax?: number | null;
          discount?: number | null;
          total?: number | null;
          payment_method?: string | null;
          discount_type?: string | null;
          discount_value?: number | null;
          invoice_id?: string | null;
        };
        Update: {
          id?: string;
          created_by?: string | null;
          created_at?: string;
          status?: string | null;
          subtotal?: number | null;
          tax?: number | null;
          discount?: number | null;
          total?: number | null;
          payment_method?: string | null;
          discount_type?: string | null;
          discount_value?: number | null;
          invoice_id?: string | null;
        };
        Relationships: [];
      };
      pos_transaction_items: {
        Row: {
          id: string;
          transaction_id: string;
          item_type: string;
          item_id: string;
          item_code: string | null;
          item_name: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          discount: number | null;
        };
        Insert: {
          id?: string;
          transaction_id: string;
          item_type: string;
          item_id: string;
          item_code?: string | null;
          item_name: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          discount?: number | null;
        };
        Update: {
          id?: string;
          transaction_id?: string;
          item_type?: string;
          item_id?: string;
          item_code?: string | null;
          item_name?: string;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          discount?: number | null;
        };
        Relationships: [];
      };
      lobby_games: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          hourly_price: number | null;
          image_url: string | null;
          is_available: boolean | null;
          max_players: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          hourly_price?: number | null;
          image_url?: string | null;
          is_available?: boolean | null;
          max_players?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          hourly_price?: number | null;
          image_url?: string | null;
          is_available?: boolean | null;
          max_players?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      lobby_game_passes: {
        Row: {
          id: string;
          lobby_game_id: string | null;
          order_id: string | null;
          pass_code: string | null;
          customer_name: string;
          hours_purchased: number;
          start_time: string | null;
          end_time: string | null;
          status: string | null;
          created_at: string;
          activated_at: string | null;
          expires_at: string | null;
          is_active: boolean | null;
          activated_by: string | null;
          booking_id: string | null;
          user_id: string | null;
          duration_minutes: number | null;
        };
        Insert: {
          id?: string;
          lobby_game_id?: string | null;
          order_id?: string | null;
          pass_code?: string | null;
          customer_name: string;
          hours_purchased?: number;
          start_time?: string | null;
          end_time?: string | null;
          status?: string | null;
          created_at?: string;
          activated_at?: string | null;
          expires_at?: string | null;
          is_active?: boolean | null;
          activated_by?: string | null;
          booking_id?: string | null;
          user_id?: string | null;
          duration_minutes?: number | null;
        };
        Update: {
          id?: string;
          lobby_game_id?: string | null;
          order_id?: string | null;
          pass_code?: string | null;
          customer_name?: string;
          hours_purchased?: number;
          start_time?: string | null;
          end_time?: string | null;
          status?: string | null;
          created_at?: string;
          activated_at?: string | null;
          expires_at?: string | null;
          is_active?: boolean | null;
          activated_by?: string | null;
          booking_id?: string | null;
          user_id?: string | null;
          duration_minutes?: number | null;
        };
        Relationships: [];
      };
      pricing_tiers: {
        Row: {
          id: string;
          game_id: string | null;
          min_participants: number;
          max_participants: number;
          discount_percentage: number;
          is_active: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          game_id?: string | null;
          min_participants: number;
          max_participants: number;
          discount_percentage?: number;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string | null;
          min_participants?: number;
          max_participants?: number;
          discount_percentage?: number;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      roles: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          permissions: Json;
          is_system_role: boolean | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          permissions?: Json;
          is_system_role?: boolean | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          permissions?: Json;
          is_system_role?: boolean | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role_id: string;
          assigned_at: string;
          assigned_by: string | null;
          is_active: boolean | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          role_id: string;
          assigned_at?: string;
          assigned_by?: string | null;
          is_active?: boolean | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          role_id?: string;
          assigned_at?: string;
          assigned_by?: string | null;
          is_active?: boolean | null;
        };
        Relationships: [];
      };
      site_settings: {
        Row: {
          id: string;
          setting_key: string;
          setting_value: Json;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          setting_key: string;
          setting_value: Json;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          setting_key?: string;
          setting_value?: Json;
          created_at?: string;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      page_seo: {
        Row: {
          id: string;
          page_identifier: string;
          meta_title: string | null;
          meta_description: string | null;
          keywords: string | null;
          canonical_url: string | null;
          robots: string | null;
          og_title: string | null;
          og_description: string | null;
          og_image_url: string | null;
          is_active: boolean | null;
          priority: number | null;
          change_frequency: string | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          page_identifier: string;
          meta_title?: string | null;
          meta_description?: string | null;
          keywords?: string | null;
          canonical_url?: string | null;
          robots?: string | null;
          og_title?: string | null;
          og_description?: string | null;
          og_image_url?: string | null;
          is_active?: boolean | null;
          priority?: number | null;
          change_frequency?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          page_identifier?: string;
          meta_title?: string | null;
          meta_description?: string | null;
          keywords?: string | null;
          canonical_url?: string | null;
          robots?: string | null;
          og_title?: string | null;
          og_description?: string | null;
          og_image_url?: string | null;
          is_active?: boolean | null;
          priority?: number | null;
          change_frequency?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      testimonials: {
        Row: {
          id: string;
          customer_name: string;
          customer_role: string | null;
          customer_avatar_url: string | null;
          rating: number;
          testimonial_text: string;
          is_featured: boolean | null;
          display_order: number | null;
          is_active: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_name: string;
          customer_role?: string | null;
          customer_avatar_url?: string | null;
          rating?: number;
          testimonial_text: string;
          is_featured?: boolean | null;
          display_order?: number | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_name?: string;
          customer_role?: string | null;
          customer_avatar_url?: string | null;
          rating?: number;
          testimonial_text?: string;
          is_featured?: boolean | null;
          display_order?: number | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      smtp_settings: {
        Row: {
          id: string;
          smtp_host: string;
          smtp_port: number;
          smtp_username: string;
          smtp_password: string;
          from_email: string;
          from_name: string;
          use_tls: boolean | null;
          is_active: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          smtp_host?: string;
          smtp_port?: number;
          smtp_username: string;
          smtp_password: string;
          from_email: string;
          from_name?: string;
          use_tls?: boolean | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          smtp_host?: string;
          smtp_port?: number;
          smtp_username?: string;
          smtp_password?: string;
          from_email?: string;
          from_name?: string;
          use_tls?: boolean | null;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      email_templates: {
        Row: {
          id: string;
          template_key: string;
          subject: string;
          html_body: string;
          text_body: string | null;
          variables: Json;
          is_active: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          template_key: string;
          subject: string;
          html_body: string;
          text_body?: string | null;
          variables?: Json;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          template_key?: string;
          subject?: string;
          html_body?: string;
          text_body?: string | null;
          variables?: Json;
          is_active?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      email_logs: {
        Row: {
          id: string;
          to_email: string;
          from_email: string;
          subject: string;
          template_key: string | null;
          status: string;
          error_message: string | null;
          sent_at: string | null;
          created_at: string;
          deduplication_id?: string | null;
        };
        Insert: {
          id?: string;
          to_email: string;
          from_email: string;
          subject: string;
          template_key?: string | null;
          status?: string;
          error_message?: string | null;
          sent_at?: string | null;
          created_at?: string;
          deduplication_id?: string | null;
        };
        Update: {
          id?: string;
          to_email?: string;
          from_email?: string;
          subject?: string;
          template_key?: string | null;
          status?: string;
          error_message?: string | null;
          sent_at?: string | null;
          created_at?: string;
          deduplication_id?: string | null;
        };
      };
      popup_banner_settings: {
        Row: {
          id: string;
          is_enabled: boolean;
          title: string | null;
          description: string | null;
          image_url: string | null;
          button_text: string | null;
          button_url: string | null;
          show_on_load: boolean;
          delay_seconds: number;
          show_once_per_session: boolean;
          background_color: string | null;
          text_color: string | null;
          button_color: string | null;
          created_at: string;
          updated_at: string;
          banner_width: number;
          banner_height: number;
          mobile_image_url: string | null;
        };
        Insert: {
          id?: string;
          is_enabled?: boolean;
          title?: string | null;
          description?: string | null;
          image_url?: string | null;
          button_text?: string | null;
          button_url?: string | null;
          show_on_load?: boolean;
          delay_seconds?: number;
          show_once_per_session?: boolean;
          background_color?: string | null;
          text_color?: string | null;
          button_color?: string | null;
          created_at?: string;
          updated_at?: string;
          banner_width?: number;
          banner_height?: number;
          mobile_image_url?: string | null;
        };
        Update: {
          id?: string;
          is_enabled?: boolean;
          title?: string | null;
          description?: string | null;
          image_url?: string | null;
          button_text?: string | null;
          button_url?: string | null;
          show_on_load?: boolean;
          delay_seconds?: number;
          show_once_per_session?: boolean;
          background_color?: string | null;
          text_color?: string | null;
          button_color?: string | null;
          created_at?: string;
          updated_at?: string;
          banner_width?: number;
          banner_height?: number;
          mobile_image_url?: string | null;
        };
        Relationships: [];
      };
      video_requests: {
        Row: {
          id: string;
          user_id: string | null;
          booking_reference: string;
          video_type: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          delivery_method: string;
          special_instructions: string | null;
          status: string;
          price: number;
          admin_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          booking_reference: string;
          video_type: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          delivery_method: string;
          special_instructions?: string | null;
          status?: string;
          price: number;
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          booking_reference?: string;
          video_type?: string;
          customer_name?: string;
          customer_email?: string;
          customer_phone?: string;
          delivery_method?: string;
          special_instructions?: string | null;
          status?: string;
          price?: number;
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contact_messages: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          subject: string;
          message: string;
          status: string;
          admin_notes: string | null;
          admin_reply: string | null;
          replied_at: string | null;
          replied_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone?: string | null;
          subject: string;
          message: string;
          status?: string;
          admin_notes?: string | null;
          admin_reply?: string | null;
          replied_at?: string | null;
          replied_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          subject?: string;
          message?: string;
          status?: string;
          admin_notes?: string | null;
          admin_reply?: string | null;
          replied_at?: string | null;
          replied_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      google_integration_settings: {
        Row: {
          id: string;
          is_active: boolean | null;
          place_id: string;
          google_maps_url: string | null;
          write_review_url: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          is_active?: boolean | null;
          place_id: string;
          google_maps_url?: string | null;
          write_review_url?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          is_active?: boolean | null;
          place_id?: string;
          google_maps_url?: string | null;
          write_review_url?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      google_rating_cache: {
        Row: {
          place_id: string;
          avg_rating: number | null;
          total_reviews: number | null;
          updated_at: string | null;
        };
        Insert: {
          place_id: string;
          avg_rating?: number | null;
          total_reviews?: number | null;
          updated_at?: string | null;
        };
        Update: {
          place_id?: string;
          avg_rating?: number | null;
          total_reviews?: number | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      google_reviews_cache: {
        Row: {
          id: string;
          place_id: string;
          author_name: string | null;
          rating: number | null;
          text: string | null;
          relative_time: string | null;
          time: string | null;
          profile_photo_url: string | null;
          google_review_url: string | null;
          raw: Json | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          place_id: string;
          author_name?: string | null;
          rating?: number | null;
          text?: string | null;
          relative_time?: string | null;
          time?: string | null;
          profile_photo_url?: string | null;
          google_review_url?: string | null;
          raw?: Json | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          place_id?: string;
          author_name?: string | null;
          rating?: number | null;
          text?: string | null;
          relative_time?: string | null;
          time?: string | null;
          profile_photo_url?: string | null;
          google_review_url?: string | null;
          raw?: Json | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      public_payment_settings: {
        Row: {
          id: string;
          provider: string;
          mode: 'test' | 'live';
          publishable_key: string | null;
          merchant_id: string | null;
          is_active: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
      };
    };
    Functions: {
      calculate_booking_price: {
        Args: {
          p_game_id: string;
          p_num_participants: number;
        };
        Returns: {
          base_price: number;
          discount_percentage: number;
          discount_amount: number;
          subtotal: number;
          vat_amount: number;
          final_price: number;
        }[];
      };
    };
    Enums: {
      user_role: UserRole;
      booking_type: BookingType;
      booking_status: BookingStatus;
      payment_status: PaymentStatus;
      payment_method: PaymentMethod;
      order_type: OrderType;
      review_source: ReviewSource;
      difficulty_level: DifficultyLevel;
    };
  };
}
